/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbsRouteImport } from './routes/abs'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CostRouteImport } from './routes/cost'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as FormulationRouteImport } from './routes/formulation'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as PatentsRouteImport } from './routes/patents'
import { Route as PriorArtRouteImport } from './routes/prior-art'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SourcesRouteImport } from './routes/sources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsRoute = AbsRouteImport.update({
  id: '/abs',
  path: '/abs',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulationRoute = FormulationRouteImport.update({
  id: '/formulation',
  path: '/formulation',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PatentsRoute = PatentsRouteImport.update({
  id: '/patents',
  path: '/patents',
  getParentRoute: () => rootRouteImport,
} as any)
const PriorArtRoute = PriorArtRouteImport.update({
  id: '/prior-art',
  path: '/prior-art',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abs': typeof AbsRoute
  '/assistant': typeof AssistantRoute
  '/cost': typeof CostRoute
  '/expert': typeof ExpertRoute
  '/formulation': typeof FormulationRoute
  '/international': typeof InternationalRoute
  '/knowledge': typeof KnowledgeRoute
  '/patents': typeof PatentsRoute
  '/prior-art': typeof PriorArtRoute
  '/reports': typeof ReportsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abs': typeof AbsRoute
  '/assistant': typeof AssistantRoute
  '/cost': typeof CostRoute
  '/expert': typeof ExpertRoute
  '/formulation': typeof FormulationRoute
  '/international': typeof InternationalRoute
  '/knowledge': typeof KnowledgeRoute
  '/patents': typeof PatentsRoute
  '/prior-art': typeof PriorArtRoute
  '/reports': typeof ReportsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abs': typeof AbsRoute
  '/assistant': typeof AssistantRoute
  '/cost': typeof CostRoute
  '/expert': typeof ExpertRoute
  '/formulation': typeof FormulationRoute
  '/international': typeof InternationalRoute
  '/knowledge': typeof KnowledgeRoute
  '/patents': typeof PatentsRoute
  '/prior-art': typeof PriorArtRoute
  '/reports': typeof ReportsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abs'
    | '/assistant'
    | '/cost'
    | '/expert'
    | '/formulation'
    | '/international'
    | '/knowledge'
    | '/patents'
    | '/prior-art'
    | '/reports'
    | '/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abs'
    | '/assistant'
    | '/cost'
    | '/expert'
    | '/formulation'
    | '/international'
    | '/knowledge'
    | '/patents'
    | '/prior-art'
    | '/reports'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/abs'
    | '/assistant'
    | '/cost'
    | '/expert'
    | '/formulation'
    | '/international'
    | '/knowledge'
    | '/patents'
    | '/prior-art'
    | '/reports'
    | '/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbsRoute: typeof AbsRoute
  AssistantRoute: typeof AssistantRoute
  CostRoute: typeof CostRoute
  ExpertRoute: typeof ExpertRoute
  FormulationRoute: typeof FormulationRoute
  InternationalRoute: typeof InternationalRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PatentsRoute: typeof PatentsRoute
  PriorArtRoute: typeof PriorArtRoute
  ReportsRoute: typeof ReportsRoute
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abs': {
      id: '/abs'
      path: '/abs'
      fullPath: '/abs'
      preLoaderRoute: typeof AbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulation': {
      id: '/formulation'
      path: '/formulation'
      fullPath: '/formulation'
      preLoaderRoute: typeof FormulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patents': {
      id: '/patents'
      path: '/patents'
      fullPath: '/patents'
      preLoaderRoute: typeof PatentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prior-art': {
      id: '/prior-art'
      path: '/prior-art'
      fullPath: '/prior-art'
      preLoaderRoute: typeof PriorArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbsRoute: AbsRoute,
  AssistantRoute: AssistantRoute,
  CostRoute: CostRoute,
  ExpertRoute: ExpertRoute,
  FormulationRoute: FormulationRoute,
  InternationalRoute: InternationalRoute,
  KnowledgeRoute: KnowledgeRoute,
  PatentsRoute: PatentsRoute,
  PriorArtRoute: PriorArtRoute,
  ReportsRoute: ReportsRoute,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
